---
collections:
  - name: cloud.terraform
    version: 3.1.0

roles:
  - name: geerlingguy.security
    version: 3.0.0

  - name: geerlingguy.firewall
    version: 2.7.0
  
  - name: geerlingguy.docker
    version: 7.9.0

